### ISSUE TITLE
Will you release the trained checkpoints of MaskedMimic?

### ISSUE THREAD

**Issue by hdadong** [NVlabs/ProtoMotions#6]

**Comment by tesslerc** [comment]
We hope to release the model weights for both the full-body tracker (phase 1) and MaskedMimic (phase 2) and are actively working towards this goal.
Hopefully we will have positive news in the next few weeks.

**Comment by hdadong** [comment]
Any new developments on this?

**Comment by tesslerc** [comment]
Yes, we've released the weights earlier this week: https://github.com/NVlabs/ProtoMotions/tree/main/data/pretrained_models/MaskedMimic

See the main readme for an example how to run.

**Comment by hdadong** [comment]
When i try to run the following code:
```bash
python phys_anim/eval_agent.py +robot=smplx +backbone=isaacgym +motion_file=/home/bigeast/ProtoMotions/data/amass/ACCAD/Male2MartialArtsPunches_c3d-smplx/E3____cross_left_stageii.npy  +checkpoint=/home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/last.ckpt
```
I got the bug here:
```bash
(promotions) (base) bigeast@bigeast:~/ProtoMotions$ python phys_anim/eval_agent.py +robot=smplx +backbone=isaacgym +motion_file=/home/bigeast/ProtoMotions/data/amass/ACCAD/Male2MartialArtsPunches_c3d-smplx/E3____cross_left_stageii.npy  +checkpoint=/home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/la
st.ckpt
Importing module 'gym_38' (/home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
2024-10-24 15:27:05,913 - INFO - logger - logger initialized
phys_anim/eval_agent.py:66: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config")
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Loading training config file from /home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/config.yaml
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

PyTorch version 2.2.0+cu121
Device count 1
/home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/bigeast/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/bigeast/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Will spawn a total of 21 objects.
Will spawn 21 scenes.
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Creating ground plane
Ground plane created
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Using VHACD cache directory '/home/bigeast/.isaacgym/vhacd'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/341ef2d97f0f9091183903d8843a24ef.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/b08dc9e0fd675e6664adc666ed4e2ec1.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/8918d572cff6b15df36ecf951968a8b0.obj'
Loading object assets... ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  10% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/e7d0920ba8d4b1be71424c004dd7ab2f.obj'
Loading object assets... ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  14% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/StraightChairs/52d41eb69bb764e784aeb682b234df80.obj'
Loading object assets... ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  19% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/277231dcb7261ae4a9fe1734a6086750.obj'
Loading object assets... ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  24% 0:00:05Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/49a60133d6b05b8d19fb4103277a6b93.obj'
Loading object assets... ━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━  29% 0:00:08Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/8918d572cff6b15df36ecf951968a8b0.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/b08dc9e0fd675e6664adc666ed4e2ec1.obj'
Loading object assets... ━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━  38% 0:00:07Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/277231dcb7261ae4a9fe1734a6086750.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/341ef2d97f0f9091183903d8843a24ef.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/HighStools/758649ba384b28856dc24db120ad1ab9.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━  52% 0:00:05Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/HighStools/d06b3f46fd5a901d4854921d37f7e048.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/cacb9133bc0ef01f7628281ecb18112.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  62% 0:00:04Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/StraightChairs/243ab0d808fae5b76f1d1c49624bcfed.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/11040f463a3895019fb4103277a6b93.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━  71% 0:00:03Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/a4e5a85d21a6b36ba60a29091f2ab01f.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/614b46cfcbe04994d91158b2b7873a40.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/c2b65540d51fada22bfa21768064df9c.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━  86% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/614b46cfcbe04994d91158b2b7873a40.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/a4e5a85d21a6b36ba60a29091f2ab01f.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
=========== Total number of unique objects is 21
Creating 1 environments... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
=========== Building object playground
Spawning a4e5a85d21a6b36ba60a29091f2ab01f.urdf ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
/home/bigeast/ProtoMotions/phys_anim/utils/motion_lib.py:154: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(key_body_ids, dtype=torch.long, device=device),
Loading motions from yaml/npy file
Loading 1/1 motion files: /home/bigeast/ProtoMotions/data/amass/ACCAD/Male2MartialArtsPunches_c3d-smplx/E3____cross_left_stageii.npy
Loaded 1 motions with a total length of 3.233s.
Loaded 1 sub motions with a total trainable length of 3.233s.
Error executing job with overrides: ['+robot=smplx', '+backbone=isaacgym', '+motion_file=/home/bigeast/ProtoMotions/data/amass/ACCAD/Male2MartialArtsPunches_c3d-smplx/E3____cross_left_stageii.npy', '+checkpoint=/home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/last.ckpt']
Error in call to target 'phys_anim.envs.masked_mimic.isaacgym.MaskedMimicHumanoid':
ValueError("'L_Hand' is not in list")
full_key: env

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by hdadong** [comment]
Then I delete the code related to 'L_hand' and 'R_hand' in data/pretrained_models/config.yaml, 
I got the another bug here:
```base
(promotions) (base) bigeast@bigeast:~/ProtoMotions$ python phys_anim/eval_agent.py +robot=smplx +backbone=isaacgym +motion_file=/home/bigeast/ProtoMotions/data/amass/ACCAD/Female1General_c3d-smplx/A1___Stand_stageii.npy   +checkpoint=/home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/last.ckpt
Importing module 'gym_38' (/home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
2024-10-24 15:49:14,209 - INFO - logger - logger initialized
phys_anim/eval_agent.py:66: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="config")
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Loading training config file from /home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/config.yaml
You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

PyTorch version 2.2.0+cu121
Device count 1
/home/bigeast/Downloads/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/bigeast/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/bigeast/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Will spawn a total of 21 objects.
Will spawn 21 scenes.
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Creating ground plane
Ground plane created
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--Using VHACD cache directory '/home/bigeast/.isaacgym/vhacd'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/HighStools/758649ba384b28856dc24db120ad1ab9.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/c2b65540d51fada22bfa21768064df9c.obj'
Loading object assets... ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   5% -:--:--Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/8918d572cff6b15df36ecf951968a8b0.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/49a60133d6b05b8d19fb4103277a6b93.obj'
Loading object assets... ━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  14% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/e7d0920ba8d4b1be71424c004dd7ab2f.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/341ef2d97f0f9091183903d8843a24ef.obj'
Loading object assets... ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  24% 0:00:03Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/a4e5a85d21a6b36ba60a29091f2ab01f.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/StraightChairs/243ab0d808fae5b76f1d1c49624bcfed.obj'
Loading object assets... ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  33% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/341ef2d97f0f9091183903d8843a24ef.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/a4e5a85d21a6b36ba60a29091f2ab01f.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/277231dcb7261ae4a9fe1734a6086750.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━  48% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/614b46cfcbe04994d91158b2b7873a40.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/11040f463a3895019fb4103277a6b93.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━  57% 0:00:02Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/b08dc9e0fd675e6664adc666ed4e2ec1.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/HighStools/d06b3f46fd5a901d4854921d37f7e048.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Tables/614b46cfcbe04994d91158b2b7873a40.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━  71% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/StraightChairs/52d41eb69bb764e784aeb682b234df80.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━  76% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LowStools/b08dc9e0fd675e6664adc666ed4e2ec1.obj'
Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Sofas/277231dcb7261ae4a9fe1734a6086750.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━  86% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/Armchairs/cacb9133bc0ef01f7628281ecb18112.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━  90% 0:00:01Found existing convex decomposition for mesh 'phys_anim/data/assets/scenes/test/SAMP/LargeSofas/8918d572cff6b15df36ecf951968a8b0.obj'
Loading object assets... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
=========== Total number of unique objects is 21
Creating 1 environments... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
=========== Building object playground
Spawning 8918d572cff6b15df36ecf951968a8b0.urdf ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
/home/bigeast/ProtoMotions/phys_anim/utils/motion_lib.py:154: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(key_body_ids, dtype=torch.long, device=device),
Loading motions from yaml/npy file
Loading 1/1 motion files: /home/bigeast/ProtoMotions/data/amass/ACCAD/Female1General_c3d-smplx/A1___Stand_stageii.npy
Loaded 1 motions with a total length of 2.967s.
Loaded 1 sub motions with a total trainable length of 2.967s.
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/torch/nn/init.py:452: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/torch/nn/modules/transformer.py:286: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Loading model from checkpoint: /home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/last.ckpt
Error executing job with overrides: ['+robot=smplx', '+backbone=isaacgym', '+motion_file=/home/bigeast/ProtoMotions/data/amass/ACCAD/Female1General_c3d-smplx/A1___Stand_stageii.npy', '+checkpoint=/home/bigeast/ProtoMotions/data/pretrained_models/MaskedMimic/last.ckpt']
Traceback (most recent call last):
  File "phys_anim/eval_agent.py", line 121, in main
    algo.load(config.checkpoint)
  File "/home/bigeast/ProtoMotions/phys_anim/agents/ppo.py", line 223, in load
    self.load_parameters(state_dict)
  File "/home/bigeast/ProtoMotions/phys_anim/agents/amp.py", line 527, in load_parameters
    super().load_parameters(state_dict)
  File "/home/bigeast/ProtoMotions/phys_anim/agents/ppo.py", line 229, in load_parameters
    self.actor.load_state_dict(state_dict["actor"])
  File "/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/lightning/fabric/wrappers.py", line 168, in load_state_dict
    return self._original_module.load_state_dict(state_dict=state_dict, strict=strict, **kwargs)
  File "/home/bigeast/anaconda3/envs/promotions/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ActorFixedSigmaVAE:
        size mismatch for logstd: copying a param with shape torch.Size([69]) from checkpoint, the shape in current model is torch.Size([153]).
        size mismatch for mu_model.running_obs_norm.mean: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for mu_model.running_obs_norm.var: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for mu_model.trunk.0.weight: copying a param with shape torch.Size([1024, 678]) from checkpoint, the shape in current model is torch.Size([1024, 1098]).
        size mismatch for mu_model.trunk.6.weight: copying a param with shape torch.Size([69, 1024]) from checkpoint, the shape in current model is torch.Size([153, 1024]).
        size mismatch for mu_model.trunk.6.bias: copying a param with shape torch.Size([69]) from checkpoint, the shape in current model is torch.Size([153]).
        size mismatch for vae_encoder.trunk.running_obs_norm.mean: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for vae_encoder.trunk.running_obs_norm.var: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for vae_encoder.trunk.trunk.0.weight: copying a param with shape torch.Size([1024, 5074]) from checkpoint, the shape in current model is torch.Size([1024, 10494]).
        size mismatch for vae_encoder.trunk.extra_input_models.mimic_target_poses.running_obs_norm.mean: copying a param with shape torch.Size([4320]) from checkpoint, the shape in current model is torch.Size([9360]).
        size mismatch for vae_encoder.trunk.extra_input_models.mimic_target_poses.running_obs_norm.var: copying a param with shape torch.Size([4320]) from checkpoint, the shape in current model is torch.Size([9360]).
        size mismatch for vae_prior.trunk.obs_encoder.running_obs_norm.mean: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for vae_prior.trunk.obs_encoder.running_obs_norm.var: copying a param with shape torch.Size([358]) from checkpoint, the shape in current model is torch.Size([778]).
        size mismatch for vae_prior.trunk.obs_encoder.trunk.0.weight: copying a param with shape torch.Size([256, 358]) from checkpoint, the shape in current model is torch.Size([256, 778]).
        size mismatch for vae_prior.trunk.extra_input_models.historical_pose_obs.running_obs_norm.mean: copying a param with shape torch.Size([217]) from checkpoint, the shape in current model is torch.Size([469]).
        size mismatch for vae_prior.trunk.extra_input_models.historical_pose_obs.running_obs_norm.var: copying a param with shape torch.Size([217]) from checkpoint, the shape in current model is torch.Size([469]).
        size mismatch for vae_prior.trunk.extra_input_models.historical_pose_obs.trunk.0.weight: copying a param with shape torch.Size([256, 217]) from checkpoint, the shape in current model is torch.Size([256, 469]).
        size mismatch for vae_prior.trunk.extra_input_models.masked_mimic_target_poses.running_obs_norm.mean: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([132]).
        size mismatch for vae_prior.trunk.extra_input_models.masked_mimic_target_poses.running_obs_norm.var: copying a param with shape torch.Size([184]) from checkpoint, the shape in current model is torch.Size([132]).
        size mismatch for vae_prior.trunk.extra_input_models.masked_mimic_target_poses.trunk.0.weight: copying a param with shape torch.Size([256, 184]) from checkpoint, the shape in current model is torch.Size([256, 132]).

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```


It seem the network shape of the checkpoint is not align with the predefine value in config.

**Comment by tesslerc** [comment]
Just checking -- is it working ok or are you encountering any issues running?
I saw there was some issue, but you've since edited.

**Comment by hdadong** [comment]
I have fixed the bug by change the smplx to smpl and successfully run the code. But i still don't know how to control the humanoid by language or keyboard input.

**Comment by tesslerc** [comment]
You can't control using the keyboard. What you can do in "user control" mode is specify some constraints through a YAML file.
I hope to add direct keyboard/mouse control in the future.

There's some more info on the user-control scheme in this thread: https://x.com/ChenTessler/status/1847923677020471799
